### ISSUE TITLE
Issue with python 3.7

### ISSUE THREAD

**Issue by mystdeim** [HDE/python-lambda-local#53] opened 2019-10-31 13:02 UTC
I get this error:

```
Traceback (most recent call last):
  File "/home/*****/myproject/bin/python-lambda-local", line 5, in <module>
    from lambda_local import main
  File "/home/*****/myproject/lib/python3.7/site-packages/lambda_local/__init__.py", line 12, in <module>
    from .main import run
  File "/home/*****/myproject/lib/python3.7/site-packages/lambda_local/main.py", line 25, in <module>
    urllib3.disable_warnings()
AttributeError: module 'botocore.vendored.requests.packages.urllib3' has no attribute 'disable_warnings'
```

I just installed new ubuntu 19.04 with python 3.7, with python 3.6 I didn't have a such issue

**Comment by yxd-hde** [comment] 2019-11-01 04:41
Duplicate of #31

**Closed by yxd-hde** 2019-11-01 04:41 UTC
