### ISSUE TITLE
ModuleNotFoundError: No module named 'request-202c45fb-86df-42ab-97ed-e5c6b298392d'

### ISSUE THREAD

**Issue by AbhimanyuHK** [HDE/python-lambda-local#45] opened 2019-02-12 11:04 UTC
python-local-lambda : 0.1.8
python : 3.7 and 3.6

When i run : `python-lambda-local -f handler my-test.py event.json`
Getting Module Not Found Error

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\abimanyu\AppData\Local\Programs\Python\Python36\Lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\abimanyu\AppData\Local\Programs\Python\Python36\Lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
ModuleNotFoundError: No module named 'request-202c45fb-86df-42ab-97ed-e5c6b298392d'
```

**Comment by freedomofkeima** [comment] 2019-02-12 12:25
Hi,

Thanks for the report. Unfortunately, I'm not familiar with Windows environment and this issue is related to the behavior of `multiprocessing` in Windows (Python >= 3.6). Specifically:

> On Windows only 'spawn' is available. On Unix 'fork' and 'spawn' are always supported, with 'fork' being the default.

And so it seems, the error message above is caused by passing a module as an argument under `spawn` start method.

For time being, there is no clear timeline when this issue will be fixed. Of course, if you find a way to fix it, feel free to open a PR and it will be greatly appreciated.

Thanks.

**Comment by victorlarios** [comment] 2019-02-20 02:43
Same thing with:

python-local-lambda : 0.1.8
python : 2.7

Had to move to 0.1.7 to make it work.

Regards.

**Comment by CrlsPerez** [comment] 2019-02-20 06:15
> Same thing with:
> 
> python-local-lambda : 0.1.8
> python : 2.7
> 
> Had to revert to 0.1.7 to make it work.
> 
> Regards.

Tx my friend.

**Comment by demo2327** [comment] 2019-05-20 17:29
I had the same issue running with python versions 3.6 and 3.7, using a very simple hello world app. I found the error was caused by my simple function not taking event and context, and when added the problems were solved for 2.7 and both 3.6 version.

**before :**  
def handler(event):
    print("Good Morning World, wtf")

**after**
def handler(event, context):
    print("Good Morning World, wtf")

**Comment by d4nielfr4nco** [comment] 2019-12-02 10:58
Still having this problem. It seems that it only works with python 2.7 on windows.

**Comment by yxd-hde** [comment] 2019-12-04 08:42
Maybe it is related to:

https://github.com/HDE/python-lambda-local/blob/3aa330964a6929df7f09f0edd25095d490c9679c/lambda_local/main.py#L105

**Closed** 2019-12-10 03:00 UTC
Labels: help wanted, windows

**Comment by nbaghiro** [comment] 2021-07-27 17:37
@yxd-hde - this is still happening for me and I am on MacOS, as soon as I start processes it gives me the following error 
```
ModuleNotFoundError: No module named 'request-37c3cac7-24cf-4d56-9de5-857ebb78b905'
```
